image: node:18.0		#镜像版本
stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - build
  only:
    - test			#build分支为test
  script:
    - echo "hello docker!"
    - pwd
    - ls
    - npm install		#下载包
    - npm run build		#编译文件
    - ls
  cache:
    key: "$CI_JOB_NAME"	
    paths:
      - node_modules/		#缓存包，避免重新下载
  artifacts:
    paths:
      - build/			#将编译后的文件打包供下载
    expire_in: 1 week    

deploy:
  stage: deploy
  tags:
    - deploy
  only:
    - test
  script:
    - echo "hello deploy"
  cache:
    key: "$CI_JOB_NAME"	
    paths:
      - node_modules/		#缓存包，避免重新下载