/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  tutorialSidebar1: [{type: 'autogenerated', dirName: '01.java'}],
  tutorialSidebar2: [{type: 'autogenerated', dirName: '02.algorithm'}],
  tutorialSidebar3: [{type: 'autogenerated', dirName: '03.operation'}],
  tutorialSidebar4: [{type: 'autogenerated', dirName: '04.database'}],
  tutorialSidebar5: [{type: 'autogenerated', dirName: '05.virtualization'}],
  tutorialSidebar6: [{type: 'autogenerated', dirName: '06.network'}],
  tutorialSidebar7: [{type: 'autogenerated', dirName: '07.interview'}],
  tutorialSidebar8: [{type: 'autogenerated', dirName: '08.project'}],
  
};

export default sidebars;
